before:
  hooks:
    - go mod init link
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/link
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goflags:
      - "-trimpath"
    ldflags:
      - "-s -w"

archives:
  - format: tar.gz
    name_template: "link_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: false
  mode: replace
