version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/passport
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: true
  mode: replace
