name: Coveralls Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.1

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Run tests with coverage
      run: go test -covermode=count -coverprofile=coverage.out ./...

    - name: Upload to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
